# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Amna Rahman
title: Language Data Analyst
email: amnarahman00@gmail.com
website: www.github.com/amna-rahman

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: amna-rahman
linkedin_username: amnarahman



# About Section
about_profile_image: images/profile.jpg
about_content: |
  Hi, I am Amna Rahman, a Language Data Analyst with a strong background in Natural Language Processing, AWS, and Data Analysis. I am passionate about exploring AI translation systems and addressing linguistic biases in machine learning applications.

  I am most skilled in: <mark>AWS</mark>, <mark>Natural Language Processing</mark>, and <mark>Data Analysis</mark>

content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: CD Pipeline Using AWS
        description: |
          A CD pipeline that will deploy your web application automatically anytime your source code is updated.
          **Technologies:** GitHub, EBS, AWS CodeBuild, AWS CodePipeline

      - layout: top-middle
        title: Dockerized Blog
        description: |
          A blog application using Flask.
          **Technologies:** Flask, HTML, CSS, Python. Dockerized with Dockerfile

      - layout: top-middle
        title: Diabetes Prediction Using ML
        description: |
          Developed an end-to-end diabetes prediction system using SVM in Python.
          **Technologies:** Machine Learning, SVM, Python

      - layout: top-middle
        title: Spelling Correction with Java
        description: |
          Implemented NearbyWords and SpellingSuggest classes for spelling correction using letter mutations such as insertions, deletions, and substitutions.

      - layout: top-middle
        title: Book Genre Classification Using Text Analysis
        description: |
          Classifies books into genres based on their textual descriptions using text processing and machine learning techniques.
          **Technologies:** Python, NLTK/spaCy, Scikit-learn, Pandas, Matplotlib/Seaborn

  - title: Experience
    layout: list
    content:
      - layout: top-middle
        title: Front End Developer
        sub_title: ACM Chapter / Freelancing
        caption: 2020-2022
        description: |
          Proficient in JSON/YAML, Angular, HTML5, CSS, JavaScript, C++, and Python.
          Experienced in full-stack development, corporate site management, and cross-functional team collaboration.

      - layout: top-middle
        title: DevOps Engineer / ML OPS Internship
        sub_title: ALIVA Tech Pvt LTD
        caption: 2022-2023
        description: |
          Designed and implemented CI/CD pipelines for efficient deployment.
          Managed Docker containers, orchestrated Kubernetes clusters, and automated tasks with Bash and Python.
          Utilized Git for version control and deployed applications on AWS for optimal performance.

      - layout: top-middle
        title: Data Analyst Internship
        sub_title: AL KHIDMAT Foundation
        caption: 2024-2025
        description: |
          Proficient in SQL, Excel, Power BI, Tableau, and Python for data analysis.
          Experienced in data management, visualization, and providing insights for decision-making and process optimization.

      - layout: top-middle
        title: Language Data Analyst
        sub_title: ALIVA Tech Pvt LTD
        caption: 2023-Present
        description: |
          Analyzed text data using NLP, tokenization, and machine learning.
          Developed feature extraction models and contributed to language data processing projects.


  - title: Education
    layout: list
    content:
      - layout: top-middle
        title: Virtual University of Pakistan
        caption: 2021 - 2025
        sub_title: Bachelor of Computer Science
        description: |
          Specialized in Artificial Intelligence, Data Analysis, and Full-Stack Development. Participated in multiple academic projects related to NLP and Machine Learning.

  - title: A Little More About Me
    layout: text
    content: |
      Outside my professional life, I enjoy:
      - Traveling
      - Gaming
      - Researching AI Ethics
      - Learning new languages(

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
